# Nome da aplicação
spring.application.name=shoppmate

# Configuração do banco de dados Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/shopmate
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuração para criação/atualização automática de tabelas
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

# Configuração do Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# 1h in millisecond
jwt.token.expiration=360000